### PR TITLE
Fix: Allow running command with `switch-format` argument

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] allows running the command with `switch-format` argument

Follows https://github.com/symplify/config-transformer/issues/11#issuecomment-1410081176.

💁‍♂️ For reference, see

- https://github.com/symfony/console/blob/v6.2.0/Application.php#L1182-L1194
- https://github.com/symfony/console/blob/v6.2.0/Application.php#L1065-L1068

### CODE REVIEW

**Comment by TomasVotruba** [comment]
Thank you for this one :partying_face:

**Comment by localheinz** [comment]
Thank you, @TomasVotruba!

**Comment by TomasVotruba** [comment]
I'm trying to run this locally, and it seems it breaks the other way around:

```bash
➜  git:(tv-validation-php-to-yalm) ✗ vendor/bin/config-transformer tests/Unit/Lib/Validation/Constraint/config/config.yml 

                                                                                    
  Command "tests/Unit/Lib/Validation/Constraint/config/config.yml" is not defined.  
                                                                                    
```

I think we'll have to pick one :) 
I'd prefer the command-name-less one, even though its a BC break, as this tool will have always just one.

**Comment by localheinz** [comment]
@TomasVotruba 

Sounds good!

**Pull request merged**
