### PR TITLE
remove reference to setting Symfony version

### PR DESCRIPTION
**Pull request by tacman**
The -s option no longer exists.

### CODE REVIEW

**Comment by TomasVotruba** [comment]
This option was removed, as it was not working well.
Use the upgrade run then tune the configs manually (or rather with PHPStorm regex/replace :)) to fit your Symfony version.

**Comment by TomasVotruba** [comment]
Ah, this PR should target the monorepo: https://github.com/symplify/symplify
Could you change it there?

**Comment by tacman** [comment]
It appears to already be removed from the monorepo, perhaps the readonly
repos need to be updated.

https://github.com/symplify/symplify/tree/main/packages/config-transformer

**Comment by TomasVotruba** [comment]
It was not. I found it and removed it: https://github.com/symplify/symplify/commit/493209bb356823ca82a2f7c60abc5e16c66ebd84

**Pull request closed without merging**
